# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = 'https://fresun.github.io/'

publishDir = 'docs'

defaultContentLanguage = "en"

copyright = "© Copyright Fredrik Sundström"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
 
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"


# [privacy]
#  [privacy.vimeo]
#    enableDNT = true
#  [privacy.x]
#    enableDNT = true
#  [privacy.youTube]
#    privacyEnhanced = true

# [services]
#  [services.x]
#    disableInlineCSS = true
